language: php

php:
  - 8.0.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

env:
  global:
    - XDEBUG_MODE=coverage

install:
  - composer install --no-interaction
  - composer require scrutinizer/ocular --no-interaction

script:
  - mkdir -p ./build/logs
  - composer ci

after_script:
  - ./vendor/bin/ocular code-coverage:upload --format=php-clover ./build/logs/clover.xml
